### PR TITLE
Add group filter to stories

### PR DESCRIPTION
**Pull request by YaleChen299**
Missing Permission check.
Current behaviour of the model function is:

- if groupID is given, filter by groupID,
- if the groupID is nil, gets all stories.

In the controller, the current routing and middle ware guarantees that the list all route will have a valid groupID.

Part of #15.

### CODE REVIEW

**Comment by RichDom2185** [comment]
Blocked by #97 (depends on the same migration file).

**Review by RichDom2185 — COMMENTED** [review]
Direction looks good. Just one question: does setting to `nil` actually filter `WHERE group_id IS NULL`? Or does it simply ignore the field, can we test this behaviour?

**Comment by RichDom2185** [comment]
> Direction looks good. Just one question: does setting to `nil` actually filter `WHERE group_id IS NULL`? Or does it simply ignore the field, can we test this behaviour?

I'm asking because when setting values, we need to explicitly use an NULL expression in gorm (nil fields are simply ignored, e.g. see #85).

**Comment by YaleChen299** [comment]
> > Direction looks good. Just one question: does setting to `nil` actually filter `WHERE group_id IS NULL`? Or does it simply ignore the field, can we test this behaviour?
> 
> I'm asking because when setting values, we need to explicitly use an NULL expression in gorm (nil fields are simply ignored, e.g. see #85).

I think i have tests for that, when i use the struct where, with group id as null, it will explicit find those stories without groups.

**Comment by RichDom2185** [comment]
> Edit: passing nil will get all the stories.

Ok, I will update the PR description.

**Review by RichDom2185 — APPROVED** [review]
LGTM for now, thanks!

**Pull request merged**
